// Generated by CoffeeScript 1.8.0
(function() {
  var Producer, debug, fs, net;

  fs = require('fs');

  debug = require('debug')('fq:Producer');

  net = require('net');

  Producer = (function() {
    var validateParam;

    function Producer(config) {
      this.name = validateParam('name', config);
      this._sock = null;
      this._sock = net.connect({
        path: '/tmp/' + this.name + '.sock'
      });
      debug('Connected!');
    }

    validateParam = function(param, config) {
      if (!config[param]) {
        throw Error("Provide " + param + " in config object");
      } else {
        return config[param];
      }
    };

    Producer.prototype.push = function(msg, cb) {
      if (typeof msg !== 'string') {
        msg = msg.toString();
      }
      msg += "\n";
      return this._sock.write(msg, cb);
    };

    return Producer;

  })();

  module.exports = Producer;

}).call(this);
