// Generated by CoffeeScript 1.8.0
(function() {
  var Consumer, async, config, consumer, debug;

  Consumer = require('../Consumer');

  debug = require('debug')('fq:test');

  async = require('async');

  config = {
    name: 'foo_bar',
    path: '/tmp'
  };

  consumer = new Consumer(config);

  consumer.onMessage(function(data) {
    return debug(data);
  });

  consumer.start();

}).call(this);
