// Generated by CoffeeScript 1.8.0
(function() {
  var Producer, async, config, debug, producer;

  Producer = require('../Producer');

  debug = require('debug')('fq:test');

  async = require('async');

  config = {
    name: 'foo_bar'
  };

  producer = new Producer(config);

  setInterval(function() {
    producer.push(Math.random());
    producer.push(Math.random());
    return producer.push(Math.random());
  }, 10);

}).call(this);
