// Generated by CoffeeScript 1.8.0
(function() {
  var Server, config, debug, server;

  Server = require('../Server');

  debug = (require('debug'))('fq:testServer');

  config = {
    name: 'foo_bar',
    path: '/tmp',
    maxMessagesPerFile: 555,
    maxFileSize: 1024 * 1024
  };

  server = new Server(config);

}).call(this);
